services:
  aircraft-circle:
    image: ghcr.io/challgren/aircraft-circle:latest
    container_name: aircraft-circle
    restart: unless-stopped
    ports:
      - 8888:8888
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - TAR1090_URL=http://tar1090:80
      - ENABLE_WEB=true
      - WEB_PORT=8888
      - MIN_RADIUS=0.5
      - MAX_RADIUS=10
      - MIN_TURNS=1.5
      - MIN_GRID_LEGS=3
      - MIN_LEG_LENGTH=2.0
      - COMPACT_MODE=false
      - QUIET_MODE=false
      - UPDATE_INTERVAL=5
      - SHOW_ALL_AIRCRAFT=true
      - SHOW_TRACKS=true
      - MAX_TRACK_POINTS=50
    volumes:
      - ./data:/app/data
    tmpfs:
      - /run:exec,size=64M
      - /tmp:size=128M
    networks:
      - adsbnet

  # Example: Running with tar1090
  tar1090:
    image: ghcr.io/sdr-enthusiasts/docker-tar1090:latest
    container_name: tar1090
    restart: unless-stopped
    environment:
      - BEASTHOST=readsb
      - LAT=YOUR_LATITUDE
      - LONG=YOUR_LONGITUDE
      - TZ=UTC
    ports:
      - 8080:80
    tmpfs:
      - /run:exec,size=64M
      - /tmp:size=128M
    networks:
      - adsbnet

networks:
  adsbnet:
    driver: bridge